# Site
# repository: sproogen/resume-theme
repository: cbarrett3/portfolio-website
# favicon: images/favicon.ico

# Personal info
name: Connor Barrett
title: Student at University of Wisconsin-Madison
email: connor.barrett@wisc.edu

# Social links
github_username:  cbarrett3
# dribbble_username: jekyll
#facebook_username: connor.barrett.35
# flickr_username: jekyll
linkedin_username: connor-barrett-617418100
twitter_username: cbarrett_10
instagram_username: cah_ner
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# soundcloud_username: connorbarrett11
# leetcode_username: connorbarrett

# About Section
# about_title: About Me
about_profile_image: images/Image-3.png
about_content: | # this will include new lines to allow paragraphs
  Welcome! My name is Connor. My goal is simple: to showcase who I am, what I do, and why I do it. Enjoy!
  Who? I'm a Saint Paul, MN native, and I graduated from UW-Madison in 2019 with a degree in Computer Science. Today I reside in Saint Paul once again, and I currently 
  work as a data specialist in the Data Intelligence division at 3M.
  
  What? In addition to school work, I had the fortunate opportunity to intern with two fortune 500 companies.
  Over my college years I gained technical experience in areas such as databases (SQL, Firebase, Azure), 
  web development (React, Angular, Flask), and data analysis (pandas, power BI, R) just to name a few. 
  Today I use these skills at my job at 3M, as well as on side projects (mostly education related).
  
  Lately, I have been loving using <mark>Angular</mark> and <mark>React</mark>, and I am most interested in <mark>Web Development</mark> and <mark>Cloud Integrations</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:
   - listening to music, making music for fun, and going to concerts
   - playing futsal, soccer, hockey, rollerblading, spike ball and anything else competitive outdoors
   - chess as of recently
   - traveling, hiking and camping especially
   - photography

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
