# Site
# repository: sproogen/resume-theme
repository: cbarrett3/portfolio-website
# favicon: images/favicon.ico

# Personal info
name: Connor Barrett
title: Student at University of Wisconsin-Madison
email: connor.barrett@wisc.edu
website: https://www.connorbarrett.me

# Social links
github_username:  cbarrett3
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: connor-barrett-617418100
twitter_username: cbarrett_10
instagram_username: cah_ner
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# soundcloud_username: connorbarrett11
# leetcode_username: connorbarrett

# About Section
# about_title: About Me
about_profile_image: images/Image-3.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Connor and I'm a senior at the University of Wisconsin-Madison. While studying computer science, I have gained experience in a number of areas including web app development, database development, data manipulation, and artificial intelligence. I have also completed three internships which have all boosted my technical, teamwork, and leadership skills.

  I am most skilled using <mark>Python</mark> and <mark>Java</mark>, and I am most interested in <mark>Machine learning</mark> and <mark>Deep Learning</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software and AI, some of my other interests and hobbies are:
   - [Discovering new music](https://www.soundcloud.com/connorbarrett11)
   - Playing soccer and ice hockey
   - Traveling
   - Attending concerts frequently

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
