# Site
# repository: sproogen/resume-theme
repository: cbarrett3/portfolio-website
# favicon: images/favicon.ico

# Personal info
name: Connor Barrett
title: Data Analytics Developer at 3M
email: connor.steven.barrett@gmail.com

# Social links
github_username:  cbarrett3
# dribbble_username: jekyll
#facebook_username: connor.barrett.35
# flickr_username: jekyll
linkedin_username: connor-barrett-617418100
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# soundcloud_username: connorbarrett11
# leetcode_username: connorbarrett

# About Section
# about_title: About Me
about_profile_image: images/Image-3.png
about_content: | # this will include new lines to allow paragraphs  
  <mark>Who</mark> <br> I'm Connor. Saint Paul, MN native (and current resident). UW-Madison Alum. Developer.
  
  <mark>Technically</mark> <br>  Web Development: Front-End: html & css, react, angular, flask, materialize. Back-End: .net & entity framework. Databases: sql (teradata, azure sql db, +), nosql (firebase). Data Engineering & Analytics: python (databricks, pandas, powerbi). Automation: powershell and python scripting. 
  
   <mark>Passions</mark> <br> I'm a curious mind with a passion for learning and expressing myself in new ways. I love growing as developer, whether it means exploring new web libraries, listening to podcasts (Syntax.), or taking on side projects. I also love to dabble in making music (producing electrically or playing guitar). 
  
  Lately, I have been exploring <mark>GraphQL</mark> with <mark>React</mark>, and my primary interest is <mark>Full-Stack Web Development</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other interests and hobbies are:
   - futsal, soccer, hockey, rollerblading, biking and really anything outdoors
   - hiking, camping, exploring, and travelling in general
   - photography

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
